// Code generated by "stringer -type=rateLimitCategory"; DO NOT EDIT.

package okta

import "strconv"

const _rateLimitCategory_name = "rateLimitCoreCategoryrateLimitAppsCreateListCategoryrateLimitAppsGetUpdateDeleteCategoryrateLimitAuthnCategoryrateLimitGroupsCreateListCategoryrateLimitGroupsGetUpdateDeleteCategoryrateLimitLogsCategoryrateLimitSessionsCategoryrateLimitUsersCreateListCategoryrateLimitUsersGetByIDCategoryrateLimitUsersGetByLoginNameCategoryrateLimitUsersCreateUpdateDeleteByIDCategorycategories"

var _rateLimitCategory_index = [...]uint16{0, 21, 52, 88, 110, 143, 181, 202, 227, 259, 288, 324, 368, 378}

func (i rateLimitCategory) String() string {
	if i < 0 || i >= rateLimitCategory(len(_rateLimitCategory_index)-1) {
		return "rateLimitCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _rateLimitCategory_name[_rateLimitCategory_index[i]:_rateLimitCategory_index[i+1]]
}
