// Code generated by "stringer -type=rateLimitCategory"; DO NOT EDIT.

package okta

import "strconv"

const _rateLimitCategory_name = "coreCategoryappsCreateListCategoryappsGetUpdateDeleteCategoryauthnCategorygroupsCreateListCategorygroupsGetUpdateDeleteCategorylogsCategorysessionsCategoryusersCreateListCategoryusersGetByIdCategoryusersGetByLoginNameCategoryusersCreateUpdateDeleteByIdCategorycategories"

var _rateLimitCategory_index = [...]uint16{0, 12, 34, 61, 74, 98, 127, 139, 155, 178, 198, 225, 260, 270}

func (i rateLimitCategory) String() string {
	if i < 0 || i >= rateLimitCategory(len(_rateLimitCategory_index)-1) {
		return "rateLimitCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _rateLimitCategory_name[_rateLimitCategory_index[i]:_rateLimitCategory_index[i+1]]
}
